---
# -------------------- web deployment -------------#
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: fastpost
  name: backend-main
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      namespace: fastpost
      labels:
        app: backend
    spec:
      imagePullSecrets:
      - name: registrykey
      containers:
      - name: backend-main
        image: docker.io/hypofiasco/fastpost:latest
        env:
        - name: aliyun_logs_backend-main
          value: "stdout"
        resources:
          limits:
            memory: 1000Mi
---

# -------------------- web service -------------#
apiVersion: v1
kind: Service
metadata:
  namespace: fastpost
  name: backend-main
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
    nodePort: 30101
  type: NodePort
---
