-- upgrade --
CREATE TABLE IF NOT EXISTS `group` (
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    `created_at` DATETIME(6) NOT NULL  COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` DATETIME(6) NOT NULL  COMMENT '更新时间' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `label` VARCHAR(50) NOT NULL UNIQUE COMMENT '组名',
    `remark` VARCHAR(256) NOT NULL  COMMENT '备注' DEFAULT ''
) CHARACTER SET utf8mb4 COMMENT='分组';
CREATE TABLE IF NOT EXISTS `permission` (
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    `created_at` DATETIME(6) NOT NULL  COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` DATETIME(6) NOT NULL  COMMENT '更新时间' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `label` VARCHAR(50) NOT NULL UNIQUE COMMENT '权限名称',
    `code` VARCHAR(20) NOT NULL UNIQUE COMMENT '权限代码',
    `remark` VARCHAR(256) NOT NULL  COMMENT '备注' DEFAULT ''
) CHARACTER SET utf8mb4 COMMENT='权限';
CREATE TABLE IF NOT EXISTS `user` (
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    `created_at` DATETIME(6) NOT NULL  COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` DATETIME(6) NOT NULL  COMMENT '更新时间' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `username` VARCHAR(50) NOT NULL UNIQUE COMMENT '用户名称',
    `phone` VARCHAR(11) NOT NULL UNIQUE COMMENT '手机号',
    `password` VARCHAR(128) NOT NULL  COMMENT '密码',
    `last_login_at` DATETIME(6)   COMMENT '最近一次登录时间',
    `remark` VARCHAR(256) NOT NULL  COMMENT '备注' DEFAULT '',
    `status` SMALLINT NOT NULL  COMMENT '状态' DEFAULT 0
) CHARACTER SET utf8mb4 COMMENT='用户';
CREATE TABLE IF NOT EXISTS `address` (
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    `created_at` DATETIME(6) NOT NULL  COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` DATETIME(6) NOT NULL  COMMENT '更新时间' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `province` VARCHAR(256) NOT NULL  COMMENT '省/市',
    `city` VARCHAR(256) NOT NULL  COMMENT '城市',
    `detail` VARCHAR(256) NOT NULL  COMMENT '详情',
    `user_id` BIGINT NOT NULL,
    CONSTRAINT `fk_address_user_a828eefb` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON DELETE CASCADE
) CHARACTER SET utf8mb4 COMMENT='地址';
CREATE TABLE IF NOT EXISTS `profile` (
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    `created_at` DATETIME(6) NOT NULL  COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` DATETIME(6) NOT NULL  COMMENT '更新时间' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `info` VARCHAR(256) NOT NULL  COMMENT '信息' DEFAULT '',
    `user_id` BIGINT NOT NULL UNIQUE,
    CONSTRAINT `fk_profile_user_80190c5a` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON DELETE CASCADE
) CHARACTER SET utf8mb4 COMMENT='用户信息';
CREATE TABLE IF NOT EXISTS `aerich` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `version` VARCHAR(255) NOT NULL,
    `app` VARCHAR(20) NOT NULL,
    `content` JSON NOT NULL
) CHARACTER SET utf8mb4;
CREATE TABLE IF NOT EXISTS `group_permission` (
    `group_id` BIGINT NOT NULL,
    `permission_id` BIGINT NOT NULL,
    FOREIGN KEY (`group_id`) REFERENCES `group` (`id`) ON DELETE CASCADE,
    FOREIGN KEY (`permission_id`) REFERENCES `permission` (`id`) ON DELETE CASCADE
) CHARACTER SET utf8mb4;
CREATE TABLE IF NOT EXISTS `group_user` (
    `group_id` BIGINT NOT NULL,
    `user_id` BIGINT NOT NULL,
    FOREIGN KEY (`group_id`) REFERENCES `group` (`id`) ON DELETE CASCADE,
    FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON DELETE CASCADE
) CHARACTER SET utf8mb4;
